### ISSUE TITLE
How to handle action ?

### ISSUE THREAD

**Issue by BellRinging** [exyte/FloatingButton#3]
I tried to use button action and on tag action , both fail

**Comment by BellRinging** [comment]
even I modify the code to pass directly a SubmenuButton object , the item is not clickable

**Comment by f3dm76** [comment]
@BellRinging Could you please attach your code to reproduce?

**Comment by BellRinging** [comment]
> @BellRinging Could you please attach your code to reproduce?

Xcode 11.4.1

```
import SwiftUI
import FloatingButton

struct TestButton: View {
    
    var body: some View {
        
        let mainButton1 = AnyView(textButton())
        let mainButton2 = AnyView(textUsingButton())
//        let mainButton1 = AnyView(textUsingButton())
        let menu1 = FloatingButton(mainButtonView: self.mainButton(), buttons: [mainButton1,mainButton2])
        .straight()
            .direction(.bottom)
            .alignment(.right)
        .spacing(10)
        .initialOffset(y: -1000)
        .animation(.spring())
        
         return NavigationView{
//            Color.black
            Text("")
                    .navigationBarTitle("test", displayMode: .inline)
         .navigationBarItems(trailing: menu1)
        }
    }

    func mainButton() -> AnyView{
        return AnyView(
            Text("  +  ").frame(width:100)
        )
    }

    
//    func textButtons3() -> SubmenuButton{
//        let view = Text("textBitton").frame(width:100)
//        return SubmenuButton(buttonView: view,action: {print("1111")}
//    }
    

}

struct textButton: View {
    var body: some View {
        Text("button1")
            .frame(width: 100, height: 50).onTapGesture {
                print("testing")
        }
    }
}

struct textUsingButton: View {
    var body: some View {
        Button(action: {
                print("testing")
        }) {
            Text("Button2")
                .foregroundColor(Color.black)
                 .frame(width: 100, height: 50)
        }
    }
}


```
action didn't trigger.. and I tried modify the code to directly pass the SubmenuButton with action , still not able to trigger

**Comment by f3dm76** [comment]
This might be happening because buttons are outside the bounds of their superview, which is UIButtonBarStackView. So they are just not receiving the tap action. If you just put your menu in the middle of your screen, they all work fine.  
<img width="259" alt="Screenshot 2020-05-07 at 14 18 09" src="https://user-images.githubusercontent.com/9447630/81265622-a0b0d580-906d-11ea-8268-e10025ab3928.png">
Unfortunately currently there is another bug caused by using NavigationView together with PreferenceSetter, which you might run into later:
https://github.com/exyte/FloatingButton/issues/2
