### ISSUE TITLE
Labels on nested buttons skew circular layout

### ISSUE THREAD

**Issue by dd-mf** [exyte/FloatingButton#8]
I really like this library, but I need to have labels attached to circular (nested) buttons. I want the circular layout to be based on the core (circle) part of the buttons, ignoring the attached labels. Could you add either an option for labels, or a way to specify the geometry/size of each button to use in calculating the circular layout.

**Comment by f3dm76** [comment]
Hey @dd-mf, thank you for the kind words. I want to apologise for the delay on this one, but it seems like I won't have enough time for it for some time still. In the meantime, just some info. I don't think adding labels into the library itself is going to work, since I won't be able to provide enough customisation for their position this way. I would like for all the visual decisions about both buttons to be left to the user, that provides more freedom, I think. About specifying the geometry, I don't really see how that is going to help your case, please correct if I'm wrong on this (in any case that is not going to be an easy-to-use self explaining API). Circular coordinates are calculated based on MainButton center coord and basic sin/cos math - size is there only for the radius (which you can change manually by setting the offset anyway). So the center coord to use is correct, it is just that the center of your view is no longer the same as the center of the circle button. I think what you need to do is change the way your button determines its layout in a given coordinate - for example add extra space equal to label height to the top of you button view so that the center is still the same as button center.
